spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080
      client:
        registration:
          msvc-saludo-client:
            provider: spring
            client-id: saludo-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:80/authorized"
            scope: read
            client-name: msvc-saludo-client
        provider:
            spring:
              issuer-uri: http://127.0.0.1:8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE