name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.13-management
        ports:
          - 5672:5672
          - 15672:15672
        env:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin

      mongo-security:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret

      mongo-orchestrator:
        image: mongo:6.0
        ports:
          - 27018:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Start microservices with Docker Compose
      run: |
        docker-compose up -d
        sleep 60  # Esperar a que los servicios estén listos

    - name: Wait for services to be healthy
      run: |
        echo "Waiting for services..."
        for i in {1..30}; do
          if curl -f http://localhost:8080/api/health && \
             curl -f http://localhost:80/api/health && \
             curl -f http://localhost:8081/api/health && \
             curl -f http://localhost:8083/api/health; then
            echo "All services are ready!"
            break
          fi
          echo "Attempt $i: Services not ready yet..."
          sleep 5
        done

    - name: Run Smoke Tests
      working-directory: integration-tests
      run: mvn test -Dtest=SmokeTest

    - name: Run Integration Tests
      working-directory: integration-tests
      run: mvn clean test

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Integration Test Results
        path: integration-tests/target/surefire-reports/*.xml
        reporter: java-junit

    - name: Upload Cucumber Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-report
        path: integration-tests/target/cucumber-reports.html

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: integration-tests/target/surefire-reports/

    - name: Show service logs on failure
      if: failure()
      run: |
        docker-compose logs msvc-security
        docker-compose logs msvc-saludo
        docker-compose logs msvc-consumer
        docker-compose logs msvc-orchestrator

    - name: Cleanup
      if: always()
      run: docker-compose down -v

